spring:
  banner:
    location: classpath:banner.txt
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true

  application:
    name: flywayapp
  datasource:
    url: jdbc:mysql://schoolportal-sdamartinblazek.l.aivencloud.com:24242/defaultdb
    username: avnadmin
    password: AVNS_KKqWnEpE6UmZNf2T5Ye
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  flyway:
    baselineOnMigrate: true
    url: jdbc:mysql://schoolportal-sdamartinblazek.l.aivencloud.com:24242
    schemas: defaultdb
    user: avnadmin
    password: AVNS_KKqWnEpE6UmZNf2T5Ye #i will change my password..

public:
  endpoints: "/, /login, /student, /teacher, /classRoom, /parent"
