spring:
  banner:
    location: classpath:banner.txt
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true

  application:
    name: flywayapp

  datasource:
    url: jdbc:mysql://mysql-36bc738e-dasa-9d4f.i.aivencloud.com:28561/defaultdb
    username: avnadmin
    password: ${MYSQLDB_ROOT_PASSWORD}
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    url: jdbc:mysql://mysql-36bc738e-dasa-9d4f.i.aivencloud.com:28561
    schemas: defaultdb
    user: avnadmin
    password: ${MYSQLDB_ROOT_PASSWORD}

public:
  endpoints: "/, /login, /student, /teacher, /classRoom, /parent"
