USE
defaultdb;

-- Vložení dat do tabulky teacher
INSERT INTO teacher (teacher_name, teacher_surname)
VALUES ('Jan', 'Novák'),
       ('Petra', 'Svobodová'),
       ('Karel', 'Dvořák'),
       ('Lenka', 'Černá'),
       ('Tomáš', 'Procházka'),
       ('Jana', 'Kučerová'),
       ('Petr', 'Veselý'),
       ('Lucie', 'Horáková'),
       ('Miroslav', 'Němec'),
       ('Eva', 'Marková'),
       ('Martin', 'Pokorný'),
       ('Alena', 'Králová'),
       ('Josef', 'Fiala'),
       ('Kateřina', 'Sedláčková'),
       ('Václav', 'Kolář');

-- Vložení dat do tabulky class_room
INSERT INTO class_room (class_room_name, teacher_id)
VALUES ('1.A', 1),
       ('1.B', 2),
       ('2.A', 3),
       ('2.B', 4),
       ('3.A', 5),
       ('3.B', 6),
       ('4.A', 7),
       ('4.B', 8),
       ('5.A', 9),
       ('5.B', 10),
       ('6.A', 11),
       ('6.B', 12),
       ('7.A', 13),
       ('7.B', 14),
       ('8.A', 15),
       ('8.B', 1),
       ('9.A', 2),
       ('9.B', 3);

-- Vložení dat do tabulky student
INSERT INTO student (student_name, student_surname, class_room_id)
VALUES
-- 1.A - 20 students
('Adam', 'Svoboda', 1),
('Barbora', 'Novotná', 1),
('Cyril', 'Doležal', 1),
('Denisa', 'Poláková', 1),
('Eduard', 'Bláha', 1),
('Filip', 'Malý', 1),
('Gabriela', 'Benešová', 1),
('Hana', 'Zemanová', 1),
('Ivan', 'Krejčí', 1),
('Jana', 'Křížová', 1),
('Kamil', 'Vlček', 1),
('Lucie', 'Šimková', 1),
('Marek', 'Holý', 1),
('Nela', 'Matějková', 1),
('Ondřej', 'Urban', 1),
('Petra', 'Vávrová', 1),
('Roman', 'Hruška', 1),
('Simona', 'Růžičková', 1),
('Tomáš', 'Bartoš', 1),
('Veronika', 'Slavíková', 1),

-- 1.B - 18 students
('Aneta', 'Marešová', 2),
('Bohuslav', 'Soukup', 2),
('Cecílie', 'Kratochvílová', 2),
('Daniel', 'Bureš', 2),
('Eliška', 'Vondráčková', 2),
('František', 'Vlkový', 2),
('Gabriel', 'Mach', 2),
('Helena', 'Šťastná', 2),
('Igor', 'Adámek', 2),
('Jitka', 'Pavlíčková', 2),
('Kristýna', 'Říhová', 2),
('Leoš', 'Konečný', 2),
('Magdaléna', 'Bártková', 2),
('Norbert', 'Valenta', 2),
('Olga', 'Bednářová', 2),
('Pavel', 'Mlejnek', 2),
('Renata', 'Dušková', 2),
('Stanislav', 'Hrubý', 2),

-- 2.A - 22 students
('Andrea', 'Sedláčková', 3),
('Bedřich', 'Čech', 3),
('Carmen', 'Horáčková', 3),
('Dalibor', 'Kovář', 3),
('Emilie', 'Kolářová', 3),
('Filip', 'Navrátil', 3),
('Greta', 'Čermáková', 3),
('Hynek', 'Sýkora', 3),
('Irena', 'Mašková', 3),
('Jaroslav', 'Kraus', 3),
('Kamila', 'Adamová', 3),
('Ladislav', 'Pokorný', 3),
('Marie', 'Vítová', 3),
('Nikola', 'Burešová', 3),
('Oskar', 'Havlíček', 3),
('Petr', 'Moravec', 3),
('Radka', 'Bláhová', 3),
('Soňa', 'Prokopová', 3),
('Tereza', 'Veselá', 3),
('Viktor', 'Jelínek', 3),
('Zdeněk', 'Pospíšil', 3),
('Žaneta', 'Dostálová', 3),

-- 2.B - 17 students
('Aleš', 'Petr', 4),
('Blanka', 'Fialová', 4),
('Cyril', 'Dušek', 4),
('Denisa', 'Štěpánková', 4),
('Erik', 'Soukup', 4),
('Filip', 'Němeček', 4),
('Gábina', 'Hlavatá', 4),
('Hugo', 'Moravcová', 4),
('Ilona', 'Červenková', 4),
('Jakub', 'Voříšek', 4),
('Karolína', 'Bílá', 4),
('Lukáš', 'Sedlák', 4),
('Monika', 'Machová', 4),
('Nikol', 'Blahová', 4),
('Ondřej', 'Zahradník', 4),
('Patrik', 'Hájková', 4),
('Radim', 'Beran', 4),

-- 3.A - 19 students
('Adéla', 'Zimová', 5),
('Boris', 'Landa', 5),
('Cecílie', 'Němcová', 5),
('Daniela', 'Kubíková', 5),
('Emil', 'Bartoš', 5),
('Františka', 'Vlasáková', 5),
('Gustav', 'Vybíral', 5),
('Hedvika', 'Ševčíková', 5),
('Igor', 'Slavík', 5),
('Jarmila', 'Erbenová', 5),
('Karel', 'Fischer', 5),
('Lenka', 'Trnková', 5),
('Miloslav', 'Šimek', 5),
('Naděžda', 'Vaňková', 5),
('Oldřich', 'Ježek', 5),
('Pavlína', 'Hrubá', 5),
('Rostislav', 'Vrána', 5),
('Silvie', 'Petráková', 5),
('Tobias', 'Kočí', 5),

-- 3.B - 16 students
('Alex', 'Mašek', 6),
('Barbora', 'Novotný', 6),
('Cyril', 'Pavlík', 6),
('Diana', 'Šolcová', 6),
('Eduard', 'Janda', 6),
('Filip', 'Gregor', 6),
('Gabriela', 'Holubová', 6),
('Hynek', 'Linhart', 6),
('Iveta', 'Musilová', 6),
('Jan', 'Růžička', 6),
('Klára', 'Čížková', 6),
('Leona', 'Řezníčková', 6),
('Marek', 'Kopecký', 6),
('Nela', 'Sedláček', 6),
('Oto', 'Herman', 6),
('Petra', 'Roubalová', 6),

-- 4.A - 21 students
('Andrea', 'Žáková', 7),
('Bohumil', 'Pilař', 7),
('Cecilie', 'Bělohlávková', 7),
('David', 'Jaroš', 7),
('Ema', 'Bartůňková', 7),
('Filip', 'Dušek', 7),
('Gabriel', 'Kudrna', 7),
('Hana', 'Švecová', 7),
('Ivan', 'Toman', 7),
('Jana', 'Vítková', 7),
('Kamil', 'Drábek', 7),
('Lenka', 'Kubíčková', 7),
('Milan', 'Vacek', 7),
('Nikol', 'Kadlecová', 7),
('Otakar', 'Beránek', 7),
('Pavla', 'Štěpánová', 7),
('Radek', 'Zahradník', 7),
('Simona', 'Řeháková', 7),
('Tomáš', 'Hlaváč', 7),
('Viktorie', 'Hájek', 7),
('Zuzana', 'Nová', 7),

-- 4.B - 15 students
('Adam', 'Mráz', 8),
('Blanka', 'Král', 8),
('Cyril', 'Suk', 8),
('Dita', 'Bárta', 8),
('Emil', 'Tichý', 8),
('Filip', 'Janoušek', 8),
('Gábina', 'Prokop', 8),
('Hugo', 'Petr', 8),
('Ivana', 'Veselý', 8),
('Jakub', 'Bláha', 8),
('Kamila', 'Vlk', 8),
('Leoš', 'Beneš', 8),
('Martina', 'Dušek', 8),
('Naděžda', 'Mareš', 8),
('Ondřej', 'Kolář', 8),

-- 5.A - 20 students
('Alena', 'Mikuláš', 9),
('Boris', 'Kroupa', 9),
('Cecilie', 'Štěpánek', 9),
('Daniel', 'Vávra', 9),
('Eva', 'Vaněk', 9),
('Filip', 'Matoušek', 9),
('Gabriela', 'Mašek', 9),
('Hynek', 'Nejedlý', 9),
('Irena', 'Horák', 9),
('Josef', 'Tesař', 9),
('Klára', 'Kopecká', 9),
('Libor', 'Svatoš', 9),
('Martina', 'Jelínek', 9),
('Norbert', 'Bureš', 9),
('Olga', 'Zajíček', 9),
('Pavel', 'Sedlák', 9),
('Renata', 'Šmíd', 9),
('Stanislav', 'Vávrová', 9),
('Tereza', 'Hrubý', 9),
('Václav', 'Jindra', 9),

-- 5.B - 18 students
('Adam', 'Kořán', 10),
('Blanka', 'Macháček', 10),
('Cyril', 'Králík', 10),
('Denisa', 'Moravec', 10),
('Emil', 'Nosek', 10),
('Filip', 'Veselka', 10),
('Gábina', 'Otradovský', 10),
('Hugo', 'Brož', 10),
('Ivana', 'Řezníček', 10),
('Jakub', 'Vojtěch', 10),
('Kamila', 'Malík', 10),
('Leoš', 'Pavel', 10),
('Martina', 'Karel', 10),
('Naděžda', 'Heřman', 10),
('Ondřej', 'Daniel', 10),
('Petra', 'Radim', 10),
('Radek', 'Vlastimil', 10),
('Simona', 'Jarmil', 10),

-- 6.A - 17 students
('Aneta', 'Zdeněk', 11),
('Bohuslav', 'Luboš', 11),
('Cecilie', 'Miroslav', 11),
('Daniela', 'Otakar', 11),
('Emil', 'Vladimír', 11),
('Františka', 'Igor', 11),
('Gustav', 'Milan', 11),
('Hedvika', 'Jaromír', 11),
('Igor', 'Vít', 11),
('Jarmila', 'Vojtěch', 11),
('Karel', 'Radek', 11),
('Lenka', 'Petr', 11),
('Miloslav', 'Roman', 11),
('Naděžda', 'Pavel', 11),
('Oldřich', 'Jan', 11),
('Pavlína', 'Tomáš', 11),
('Rostislav', 'Marek', 11),

-- 6.B - 19 students
('Alex', 'Lucie', 12),
('Barbora', 'Eva', 12),
('Cyril', 'Hana', 12),
('Diana', 'Petra', 12),
('Eduard', 'Jana', 12),
('Filip', 'Alena', 12),
('Gabriela', 'Kateřina', 12),
('Hynek', 'Lenka', 12),
('Iveta', 'Marie', 12),
('Jan', 'Veronika', 12),
('Klára', 'Tereza', 12),
('Leona', 'Michaela', 12),
('Marek', 'Pavla', 12),
('Nela', 'Eliška', 12),
('Oto', 'Markéta', 12),
('Petra', 'Zuzana', 12),
('Roman', 'Andrea', 12),
('Simona', 'Monika', 12),
('Tomáš', 'Lucie', 12),

-- 7.A - 16 students
('Andrea', 'Kristýna', 13),
('Bohumil', 'Simona', 13),
('Cecilie', 'Barbora', 13),
('David', 'Nikola', 13),
('Ema', 'Karolína', 13),
('Filip', 'Adéla', 13),
('Gabriel', 'Aneta', 13),
('Hana', 'Gabriela', 13),
('Ivan', 'Hedvika', 13),
('Jana', 'Ilona', 13),
('Kamil', 'Jitka', 13),
('Lenka', 'Kamila', 13),
('Milan', 'Laura', 13),
('Nikol', 'Milena', 13),
('Otakar', 'Olga', 13),
('Pavla', 'Renata', 13),

-- 7.B - 20 students
('Adam', 'Stanislava', 14),
('Blanka', 'Viktorie', 14),
('Cyril', 'Blažena', 14),
('Dita', 'Božena', 14),
('Emil', 'Drahomíra', 14),
('Filip', 'Emilie', 14),
('Gábina', 'Ivana', 14),
('Hugo', 'Jarmila', 14),
('Ivana', 'Libuše', 14),
('Jakub', 'Mirka', 14),
('Kamila', 'Otýlie', 14),
('Leoš', 'Radmila', 14),
('Martina', 'Svatava', 14),
('Naděžda', 'Věra', 14),
('Ondřej', 'Zdena', 14),
('Petra', 'Amálie', 14),
('Radek', 'Berta', 14),
('Simona', 'Cecílie', 14),
('Tomáš', 'Dana', 14),
('Václav', 'Ester', 14),

-- 8.A - 18 students
('Alena', 'Filip', 15),
('Boris', 'Gustav', 15),
('Cecilie', 'Hynek', 15),
('Daniel', 'Ivan', 15),
('Eva', 'Jakub', 15),
('Filip', 'Kamil', 15),
('Gabriela', 'Leoš', 15),
('Hynek', 'Marek', 15),
('Irena', 'Norbert', 15),
('Josef', 'Ondřej', 15),
('Klára', 'Pavel', 15),
('Libor', 'Radek', 15),
('Martina', 'Stanislav', 15),
('Norbert', 'Tomáš', 15),
('Olga', 'Viktor', 15),
('Pavel', 'Zdeněk', 15),
('Renata', 'Adam', 15),
('Stanislav', 'Boris', 15),

-- 8.B - 17 students
('Andrea', 'Cyril', 16),
('Bohuslav', 'David', 16),
('Cecilie', 'Emil', 16),
('David', 'Filip', 16),
('Ema', 'Gabriel', 16),
('Filip', 'Hugo', 16),
('Gabriel', 'Ivan', 16),
('Hana', 'Jan', 16),
('Ivan', 'Karel', 16),
('Jana', 'Lukáš', 16),
('Kamil', 'Milan', 16),
('Lenka', 'Norbert', 16),
('Milan', 'Oldřich', 16),
('Nikol', 'Petr', 16),
('Otakar', 'Roman', 16),
('Pavla', 'Sebastian', 16),
('Radek', 'Tobias', 16),

-- 9.A - 19 students
('Adam', 'Urban', 17),
('Blanka', 'Váňa', 17),
('Cyril', 'Wolf', 17),
('Dita', 'Zelenka', 17),
('Emil', 'Žák', 17),
('Filip', 'Anděl', 17),
('Gábina', 'Baláž', 17),
('Hugo', 'Černoch', 17),
('Ivana', 'Dvořáček', 17),
('Jakub', 'Eliáš', 17),
('Kamila', 'Fojtík', 17),
('Leoš', 'Gál', 17),
('Martina', 'Hájková', 17),
('Naděžda', 'Janků', 17),
('Ondřej', 'Klimt', 17),
('Petra', 'Louda', 17),
('Radek', 'Mareček', 17),
('Simona', 'Neradová', 17),
('Tomáš', 'Opava', 17),

-- 9.B - 16 students
('Alena', 'Polášek', 18),
('Boris', 'Rýdl', 18),
('Cecilie', 'Straka', 18),
('Daniel', 'Tomek', 18),
('Eva', 'Urbanová', 18),
('Filip', 'Vacek', 18),
('Gabriela', 'Wolfová', 18),
('Hynek', 'Zahradník', 18),
('Irena', 'Žáková', 18),
('Josef', 'Anděl', 18),
('Klára', 'Balážová', 18),
('Libor', 'Černoch', 18),
('Martina', 'Dvořáčková', 18),
('Norbert', 'Eliáš', 18),
('Olga', 'Fojtíková', 18),
('Pavel', 'Gál', 18);

-- Vložení dat do tabulky parent
INSERT INTO parent (parent_name, parent_surname, parent_email, parent_phone)
VALUES ('Karel', 'Novák', 'karel.novak@example.com', '601234567'),
       ('Petra', 'Svobodová', 'petra.svobodova@example.com', '602345678'),
       ('Jan', 'Dvořák', 'jan.dvorak@example.com', '603456789'),
       ('Lenka', 'Černá', 'lenka.cerna@example.com', '604567890'),
       ('Tomáš', 'Procházka', 'tomas.prochazka@example.com', '605678901'),
       ('Jana', 'Kučerová', 'jana.kucerova@example.com', '606789012'),
       ('Petr', 'Veselý', 'petr.vesely@example.com', '607890123'),
       ('Lucie', 'Horáková', 'lucie.horakova@example.com', '608901234'),
       ('Miroslav', 'Němec', 'miroslav.nemec@example.com', '609012345'),
       ('Eva', 'Marková', 'eva.markova@example.com', '610123456'),
       ('Martin', 'Pokorný', 'martin.pokorny@example.com', '611234567'),
       ('Alena', 'Králová', 'alena.kralova@example.com', '612345678'),
       ('Josef', 'Fiala', 'josef.fiala@example.com', '613456789'),
       ('Kateřina', 'Sedláčková', 'katerina.sedlackova@example.com', '614567890'),
       ('Václav', 'Kolář', 'vaclav.kolar@example.com', '615678901'),
       ('Barbora', 'Novotná', 'barbora.novotna@example.com', '616789012'),
       ('Marek', 'Holý', 'marek.holy@example.com', '617890123'),
       ('Hana', 'Zemanová', 'hana.zemanova@example.com', '618901234'),
       ('Roman', 'Hruška', 'roman.hruska@example.com', '619012345'),
       ('Simona', 'Růžičková', 'simona.ruzickova@example.com', '620123456'),
       ('Ondřej', 'Urban', 'ondrej.urban@example.com', '621234567'),
       ('Nela', 'Matějková', 'nela.matejkova@example.com', '622345678'),
       ('Kamil', 'Vlček', 'kamil.vlcek@example.com', '623456789'),
       ('Lucie', 'Šimková', 'lucie.simkova@example.com', '624567890'),
       ('Denisa', 'Poláková', 'denisa.polakova@example.com', '625678901'),
       ('Filip', 'Malý', 'filip.maly@example.com', '626789012'),
       ('Gabriela', 'Benešová', 'gabriela.benesova@example.com', '627890123'),
       ('Ivan', 'Krejčí', 'ivan.krejci@example.com', '628901234'),
       ('Jana', 'Křížová', 'jana.krizova@example.com', '629012345'),
       ('Eduard', 'Bláha', 'eduard.blaha@example.com', '630123456');

-- Vložení dat do tabulky student_parent
-- Každý student má alespoň jednoho rodiče, více než 80% má dva rodiče
INSERT INTO student_parent (student_id, parent_id)
VALUES (1, 1),
       (1, 2),
       (2, 3),
       (2, 4),
       (3, 5),
       (3, 6),
       (4, 7),
       (4, 8),
       (5, 9),
       (5, 10),
       (6, 11),
       (6, 12),
       (7, 13),
       (7, 14),
       (8, 15),
       (8, 16),
       (9, 17),
       (9, 18),
       (10, 19),
       (10, 20),
       (11, 21),
       (12, 22),
       (12, 23),
       (13, 24),
       (13, 25),
       (14, 26),
       (14, 27),
       (15, 28),
       (15, 29),
       (16, 30),
       (16, 1),
       (17, 2),
       (17, 3),
       (18, 4),
       (19, 5),
       (19, 6),
       (20, 7),
       (20, 8),
-- pokračujte stejným způsobem pro zbytek studentů
-- zajistěte, aby více než 80% studentů mělo dva rodiče
-- a každý student měl alespoň jednoho rodiče
       (21, 9),
       (21, 10),
       (22, 11),
       (23, 12),
       (23, 13),
       (24, 14),
       (24, 15),
       (25, 16),
       (25, 17),
       (26, 18),
       (26, 19),
       (27, 20),
       (27, 21),
       (28, 22),
       (29, 23),
       (29, 24),
       (30, 25),
       (30, 26),
       (31, 27),
       (31, 28),
       (32, 29),
       (33, 30),
       (33, 1),
       (34, 2),
       (34, 3),
       (35, 4),
       (35, 5),
       (36, 6),
       (37, 7),
       (37, 8),
       (38, 9),
       (38, 10),
       (39, 11),
       (39, 12),
       (40, 13),
       (41, 14),
       (41, 15),
       (42, 16),
       (42, 17),
       (43, 18),
       (43, 19),
       (44, 20),
       (44, 21),
       (45, 22),
       (46, 23),
       (46, 24),
       (47, 25),
       (47, 26),
       (48, 27),
       (48, 28),
       (49, 29),
       (49, 30),
       (50, 1),
       (51, 2),
       (51, 3),
       (52, 4),
       (52, 5),
       (53, 6),
       (53, 7),
       (54, 8),
       (55, 9),
       (55, 10),
       (56, 11),
       (56, 12),
       (57, 13),
       (57, 14),
       (58, 15),
       (59, 16),
       (59, 17),
       (60, 18),
       (60, 19),
       (61, 20),
       (61, 21),
       (62, 22),
       (63, 23),
       (63, 24),
       (64, 25),
       (64, 26),
       (65, 27),
       (65, 28),
       (66, 29),
       (67, 30),
       (67, 1),
       (68, 2),
       (68, 3),
       (69, 4),
       (69, 5),
       (70, 6),
       (70, 7),
       (71, 8),
       (72, 9),
       (72, 10),
       (73, 11),
       (73, 12),
       (74, 13),
       (74, 14),
       (75, 15),
       (76, 16),
       (76, 17),
       (77, 18),
       (77, 19),
       (78, 20),
       (78, 21),
       (79, 22),
       (80, 23),
       (80, 24),
       (81, 25),
       (81, 26),
       (82, 27),
       (82, 28),
       (83, 29),
       (84, 30),
       (84, 1),
       (85, 2),
       (85, 3),
       (86, 4),
       (86, 5),
       (87, 6),
       (87, 7),
       (88, 8),
       (89, 9),
       (89, 10),
       (90, 11),
       (90, 12);

